### ISSUE TITLE
cell.c not found in cell.lua

### ISSUE THREAD

**Issue by spin6lock** [cloudwu/hive#1]
~/opensource/hive(branch:master*) % lua52 main.lua  
lua52: ./cell.lua:1: module 'cell.c' not found:
        no field package.preload['cell.c']
        no file '/usr/local/share/lua/5.2/cell/c.lua'
        no file '/usr/local/share/lua/5.2/cell/c/init.lua'
        no file '/usr/local/lib/lua/5.2/cell/c.lua'
        no file '/usr/local/lib/lua/5.2/cell/c/init.lua'
        no file './cell/c.lua'
        no file '/usr/local/lib/lua/5.2/cell/c.so'
        no file '/usr/local/lib/lua/5.2/loadall.so'
        no file './cell/c.so'
        no file '/usr/local/lib/lua/5.2/cell.so'
        no file '/usr/local/lib/lua/5.2/loadall.so'
        no file './cell.so'
stack traceback:
        [C]: in function 'require'
        ./cell.lua:1: in main chunk
        [C]: in function 'require'
        main.lua:1: in main chunk
        [C]: in ?

Did you forget to add cell.c file?

**Comment by cloudwu** [comment]
Run

lua test.lua

Don't execute main.lua or other .lua directly.
